### ISSUE TITLE
Dodatkowe funkcje

### ISSUE THREAD

**Issue by StayHere55** [Thefilippop1PL/iHelp#3]
- Zmiana nicku bot'a
  - Naprawienie błędu z "lastconnect" w liście adminów (pokazuje złą godzinę - tak mam dobrą godzinę na serwerze)
  - Możliwość zmiany struktury nazwy kanałów z !cch i auto-create
  - Podczas aktualizacji adminów online niech w nazwie kanałów wpisuje ilu ich jest np. Ekipa Online: 5

**Comment by makindotcc** [comment]
Dzieki. Dodalem do listy TODO.
