### ISSUE TITLE
Plik źródłowy

### ISSUE THREAD

**Issue by kubagut445** [Thefilippop1PL/iHelp#6]
Hej, byłaby możliwość otrzymania pliku źródłowego bota (przed kompilacją) w celu edycji i wykorzystania na własnym serwerze ts3?
Pozdrawiam :)

**Comment by makindotcc** [comment]
Niestety nie ale mozesz zainteresowac sie projektem [iBot](https://github.com/iBotSpeak). Niestety opcje musialbys napisac sam (jako plugin).
